EventManagementSystem/Models/VisitorRegistration.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EventManagementSystem.Models
{
    public class VisitorRegistration
    {
        [Key]
        public int VisitorId { get; set; }
        [Required(ErrorMessage = "Please Enter Visitor Name")]
        
        public string VisitorName { get; set; }
        [Required(ErrorMessage = "Please Enter Visitor Email")]
        [EmailAddress]
        [Remote("IsVisitorEmailExist", "Event", ErrorMessage = "This Email already exists!")]
        public string VisitorEmail { get; set; }
        [Required(ErrorMessage = "Please Enter Visitor Contact No")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Contact Number must be numeric")]
        [Remote("IsVisitorContactNoExist", "Event", ErrorMessage = "This Contact No already exists!")]
        public string VisitorContactNo { get; set; }
        [Required(ErrorMessage = "Please Select Visitor Date of Birth")]
        [DataType(DataType.Date)]
        public DateTime DateOfBirth { get; set; }
        [Required(ErrorMessage = "Please Select Visitor's  Gender")]
        public string Gender { get; set; }
        [Required(ErrorMessage = "Please Select Event ID")]
        public int EventId { get; set; }
        [Required]
        public string TicketNo { get; set; }
        [Required]
        [DataType(DataType.DateTime)]
        public DateTime TimeOfRegistration { get; set; }
        public Event Event { get; set; }
        
    }
}

EventManagementSystem/Controllers/ExecutiveController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using EventManagementSystem.Models;
using Rotativa;
using Rotativa.MVC;

namespace EventManagementSystem.Controllers
{
    public class ExecutiveController : Controller
    {
        //
        // GET: /Executive/
        private EMSDbContext dbContext=new EMSDbContext();
        public ActionResult Index()
        {
            if (Session["Id"] == null)
            {
                return RedirectToAction("Login", "Home")
                ;
            }
            return View();
        }
        [HttpGet]
        public ActionResult VisitorRegistration()
        {
            if (Session["Id"] == null)
            {
               return RedirectToAction("Login", "Home")
                ;
            }
            ViewBag.EventId = new SelectList(dbContext.Events, "EventId", "EventName");
            return View();
        }
        [HttpPost]
        public ActionResult VisitorRegistration(VisitorRegistration visitorRegistration)
        {
            ViewBag.EventId = new SelectList(dbContext.Events, "EventId", "EventName",visitorRegistration.EventId);
            visitorRegistration.TimeOfRegistration = DateTime.Now;
            var Visitor = dbContext.VisitorRegistrations.ToList();
            var count = Visitor.Count;
            var ZeroToBeAdded = 3;
            string number = "";
            for (int i = 0; i < ZeroToBeAdded; i++)
            {
                number += 0;
            }
            count += 1;
            visitorRegistration.TicketNo ="CODEBREAKERS" + "-" + number + count;
                dbContext.VisitorRegistrations.Add(visitorRegistration);
                dbContext.SaveChanges();
                ViewBag.msg = "Visitor Has been  succesfully registered";

                return RedirectToAction("VisitorList");
        }

        public ActionResult GetEventById(int eId)
        {
            var eEvent=
            dbContext.Events.Where(m=>m.EventId==eId);
            return Json(eEvent.ToList(), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult VisitorList()
        {
            if (Session["Id"] == null)
            {
                return RedirectToAction("Login", "Home")
                    ;
            }

            return View(dbContext.VisitorRegistrations.ToList());

        }
        [HttpGet]

        public ActionResult PrintDetails(int? Id)
        {
            var id = dbContext.VisitorRegistrations.Select(p => p.VisitorId).DefaultIfEmpty(0).Max();

            VisitorRegistration visitor = new VisitorRegistration();

            visitor = dbContext.VisitorRegistrations.Find(id);
            if (visitor == null)
            {
                return HttpNotFound();
            }

            var aVisitor = visitor;

            return View(aVisitor);

        }
        public ActionResult PrintTicket(int? id)
        {
            var printTicket = new ActionAsPdf("PrintDetails" , new {id=id});
            return printTicket;
        }

	}
}

EventManagementSystem/Views/Executive/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Executive.cshtml";
}
<marquee><h2 style="text-align: center; color: green">Welcome to Event Management System</h2> </marquee>

EventManagementSystem/Views/Executive/PrintDetails.cshtml
@using System.Web.Mvc.Html
@using EventManagementSystem.Controllers
@model EventManagementSystem.Models.VisitorRegistration


@{
    Layout = null;
}


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        * {
            box-sizing: border-box;
        }

        /* Create two equal columns that floats next to each other */
        .column {
            float: left;
            width: 19%;
            padding: 10px;
            height: 400px; /* Should be removed. Only for demonstration */
        }

        /* Clear floats after the columns */
        .row:after {
            content: "";
            display: table;
            clear: both;
        }



        .noprint {
            display: none;
        }
    </style>

    <title>Print Ticket</title>
</head>
<body>


    <div>




        <div>
            <form id="form-1">


                <div class="row">


                    <div class="column" style="background-color: #aaa;">
                        <h5><b>@Html.DisplayNameFor(model => model.VisitorName)</b></h5>
                        <h5><b>@Html.DisplayNameFor(model => model.VisitorEmail)</b></h5>
                        <h5><b>@Html.DisplayNameFor(model => model.VisitorContactNo)</b></h5>
                        <h5><b>@Html.DisplayNameFor(model => model.Gender)</b></h5>
                        <h5><b>@Html.DisplayNameFor(model => model.EventId)</b></h5>
                        <h5><b>@Html.DisplayNameFor(model => model.TicketNo)</b></h5>
                        <h5><b>@Html.DisplayNameFor(model => model.TimeOfRegistration)</b></h5>


                    </div>
                    <div class="column" style="background-color: #bbb;">
                        <h5>@Html.DisplayFor(model => model.VisitorName)</h5>
                        <h5> @Html.DisplayFor(model => model.VisitorEmail)</h5>
                        <h5> @Html.DisplayFor(model => model.VisitorContactNo)</h5>
                        <h5> @Html.DisplayFor(model => model.Gender)</h5>
                        <h5> @Html.DisplayFor(model => model.EventId)</h5>
                        <h5> @Html.DisplayFor(model => model.TicketNo)</h5>
                        <h5> @Html.DisplayFor(model => model.TimeOfRegistration)</h5>
                    </div>
                </div>
            </form>
        </div>


    </div>
</body>
</html>

EventManagementSystem/Views/Executive/VisitorList.cshtml
@model IEnumerable<EventManagementSystem.Models.VisitorRegistration>
@{
    ViewBag.Title = "PrintTicket";
    Layout = "~/Views/Shared/Executive.cshtml";

}

<h2 style="text-align: center; color: green">Print Ticket</h2>



<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.VisitorId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VisitorName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VisitorEmail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VisitorContactNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EventId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TicketNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TimeOfRegistration)
        </th>
    </tr>


    @foreach (var item in Model)
    {

        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.VisitorId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VisitorName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VisitorEmail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VisitorContactNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfBirth)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EventId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TicketNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TimeOfRegistration)
            </td>
            <td>
                <dt>
                    @Html.ActionLink("Print", "PrintTicket", new { id = item.VisitorId })
                </dt>
            </td>
        </tr>
    }

</table>

EventManagementSystem/Views/Executive/VisitorRegistration.cshtml
@model EventManagementSystem.Models.VisitorRegistration

@{
    ViewBag.Title = "VisitorRegistration";
    Layout = "~/Views/Shared/Executive.cshtml";
}

<h2 style="text-align: center; color: green">Visitor Registration</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)
        <div class="form-group">
            <label id="Name" class="control-label col-md-4"></label>
            <div class="col-md-8">
                @Html.DropDownList("EventId", null, "---Select Event---", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EventId)
            </div>
        </div>
        <div class="form-group">
            <label id="Name" class="control-label col-md-4"></label>
            <div class="col-md-8">
                <input type="text" name="venue" id="venue" class="form-control" placeholder="Event Venue" disabled="disabled" />
            </div>
        </div>
        <div class="form-group">
            <label id="Name" class="control-label col-md-4"></label>
            <div class="col-md-8">
                <input type="text" name="date" id="date" class="form-control" placeholder="Event Date" disabled="disabled" />
            </div>
        </div>
        <div class="form-group">
            <label id="Name" class="control-label col-md-4"></label>
            <div class="col-md-8">
                <input type="text" name="startTime" id="startTime" class="form-control" placeholder=" Start Time" disabled="disabled" />
            </div>
        </div>
        <div class="form-group">
            <label id="Name" class="control-label col-md-4"></label>
            <div class="col-md-8">
                <input type="text" name="endTime" id="endTime" class="form-control" placeholder="End Time" disabled="disabled" />
            </div>
        </div>


        <div class="form-group">
            <label id="Name" class="control-label col-md-4"></label>
            <div class="col-md-8">
                @Html.TextBoxFor(m => m.VisitorName, new { @id = "Name1", placeholder = " Enter Visitor Name", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.VisitorName)
            </div>
        </div>

        <div class="form-group">
            <label id="Name" class="control-label col-md-4"></label>
            <div class="col-md-8">
                @Html.TextBoxFor(m => m.VisitorEmail, new { @id = "Email1", placeholder = "  Enter Visitor  Email", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.VisitorEmail)
            </div>
        </div>

        <div class="form-group">
            <label id="Name" class="control-label col-md-4"></label>
            <div class="col-md-8">
               @Html.TextBoxFor(m => m.VisitorContactNo, new { @id = "ContactNo1", placeholder = "  Enter Visitor Contact No", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.VisitorContactNo)
            </div>
        </div>

        <div class="form-group">
            <label id="Name" class="control-label col-md-4"></label>
            <div class="col-md-8">
                <input type="date" name="DateOfBirth" id="DateOfBirth" class="form-control" placeholder="Date of Birth Date" />
                @Html.ValidationMessageFor(model => model.DateOfBirth)
            </div>
        </div>


        <div class="form-group">
            <label id="Name" class="control-label col-md-4"></label>
            <div class="col-md-8">
                @Html.RadioButtonFor(m => m.Gender, "Male")Male
                @Html.RadioButtonFor(m => m.Gender, "Female")Female
                @Html.ValidationMessageFor(model => model.Gender)
            </div>
        </div>

        <div class="form-group">
            <label id="Name" class="control-label col-md-4"></label>
            <div class="col-md-8">
                <input type="submit" value="Submit" id="Submit" class="btn btn-default" style="background-color: #4CAF50; color: white" />
                @*<input type="button" value="Print" id="Print" class="btn btn-default" style="background-color: #4CAF50; color: white" />*@
            </div>
        </div>
    </div>
}
<h3 style="text-align: center; color: green">
    @ViewBag.msg
</h3>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function () {
            $('#EventId').change(function () {
                $('#venue').empty();
                $('#date').empty();
                $('#startTime').empty();
                $('#endTime').empty();
                var eventId = $('#EventId').val();
                var jsonData = {eId:eventId };

                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetEventById", "Executive")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(jsonData),
                    dataType: "json",
                    success: function (data) {
                        var dateFormatted = new Date(parseInt(data[0].EventDate.substr(6))).toDateString();
                        var timeFormatted = new Date(parseInt(data[0].StartTime.substr(6))).toTimeString();
                        var timeFormatted1 = new Date(parseInt(data[0].EndTime.substr(6))).toTimeString();

                        $('#venue').val(data[0].EventVenue);
                        $('#date').val(dateFormatted);
                        $('#startTime').val(timeFormatted);
                        $('#endTime').val(timeFormatted1);

                    }
                });
            });

            @*$('#Submit').click(function () {

                var id = $("#EventId").val();
                var name = $("#Name1").val();
                var email = $("#Email1").val();
                var cno = $("#ContactNo1").val();
                var dob = $("#DateOfBirth").val();
                var checkedradio = $('[name="Gender"]:radio:checked').val();
                var jsonData = { EventId: id, VisitorName: name, VisitorContactNo: cno, DateOfBirth: dob, Gender: checkedradio, VisitorEmail: email };

                $.ajax({
                    type: "POST",
                    url: '@Url.Action("VisitorRegistration", "Executive")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(jsonData),
                    dataType: "json",
                    success: function (data) {


                    }
                });
            });
            var id=1;
            $('#Print').click(function () {
                var jsonData = { aid: id };
                $.ajax({
                    
                    type: "POST",
                    url: '@Url.Action("PrintTicket", "Executive")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(jsonData),
                    dataType: "json",
                    success: function (data) {


                    }
                });
            });*@
        });
    </script>
}