EventManagementSystem/Models/Event.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EventManagementSystem.Models
{
    public class Event
    {
        [Key]
        public int EventId { get; set; }
        public int UserId { get; set; }
        [Required(ErrorMessage = "Please Enter Event Name")]
        public string EventName { get; set; }
        [Required(ErrorMessage = "Please Enter Event Venue")]
        public string EventVenue { get; set; }
        [Required(ErrorMessage = "Please Enter Email")]
        [EmailAddress]
        public string OrganizerEmail { get; set; }
        [Required(ErrorMessage = "Please Enter Contact Number")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Contact Number must be numeric")]
        public string ContactNo { get; set; }
        
        [Required(ErrorMessage = "Please Enter Event Date")]
        [DataType(DataType.Date),DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime EventDate { get; set; }
        [DataType(DataType.Time)]
        public DateTime StartTime { get; set; }
        [DataType(DataType.Time)]
        public DateTime EndTime { get; set; }
        [Required]

        public string CreatedBy { get; set; }
        [DataType(DataType.DateTime)]
        public DateTime TimeOfCreation { get; set; }

        public User User { get; set; }
        public List<VisitorRegistration> VisitorRegistrations { get; set; }


    }
}

EventManagementSystem/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EventManagementSystem.Models;
using EventManagementSystem.ViewModel;

namespace EventManagementSystem.Controllers
{
    public class EventController : Controller
    {
        //
        // GET: /Event/
        private EMSDbContext dbContext = new EMSDbContext();

        public ActionResult EventIndex()
        {
            if (Session["Id"] == null)
            {
                return RedirectToAction("Login", "Home")
                    ;
            }
            return View();
        }

        [HttpGet]
        public ActionResult CreateEvent()
        {
            if (Session["Id"] == null)
            {
                return RedirectToAction("Login", "Home")
                    ;
            }
            return View();
        }

        [HttpPost]
        public ActionResult CreateEvent(Event eEvent)
        {
            eEvent.UserId = (int) Session["Id"];
            eEvent.CreatedBy = (string) Session["user"];
            eEvent.TimeOfCreation = DateTime.Now;
            bool isExist = false;
            var msg = "";

            var eventList =
                dbContext.Events.Where(m => m.EventVenue == eEvent.EventVenue && m.EventDate == eEvent.EventDate)
                    .ToList();
            if (eventList.Count == 0)
            {
                dbContext.Events.Add(eEvent);
                dbContext.SaveChanges();
                msg = "Event Information has been saved successfully";
            }
            foreach (var ev in eventList)
            {
                if ((eEvent.StartTime >= ev.StartTime && eEvent.StartTime < ev.EndTime)
                    || (eEvent.EndTime > ev.StartTime && eEvent.EndTime <= ev.StartTime))
                {
                    msg = "Event Time conflicted";
                }
                else
                {
                    dbContext.Events.Add(eEvent);
                    dbContext.SaveChanges();
                    msg = "Event Information has been saved successfully";
                }
            }


            return Json(msg, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ShowDateWiseEvent()
        {
            if (Session["Id"] == null)
            {
                return RedirectToAction("Login", "Home")
                    ;
            }
            return View();
        }

        public JsonResult ShowDateWiseEventByRange(DateTime frmDate, DateTime edDate)
        {
            var eventList = dbContext.Events.Where(x => x.EventDate >= frmDate && x.EventDate <= edDate).ToList();

            List<DateWiseEventViewModel> aList=new List<DateWiseEventViewModel>();
            foreach (var list in eventList)
            {
                DateWiseEventViewModel aModel=new DateWiseEventViewModel();
                aModel.EventName = list.EventName;
                aModel.EventVenue = list.EventVenue;
                aModel.EventDate = list.EventDate;
                aModel.StartTime = list.StartTime.ToString();
                aModel.EndTime = list.EndTime.ToString();
                aList.Add(aModel);

            }

            return Json(aList, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ShowEventWiseReport()
        {
            if (Session["Id"] == null)
            {
                return RedirectToAction("Login", "Home")
                    ;
            }
            ViewBag.EventList = dbContext.Events.ToList();

            return View();
        }

        public ActionResult GetEventVisitorByEventId(int eventID)
        {
            var visitorList = dbContext.VisitorRegistrations.Where(m => m.EventId == eventID).ToList();
            return Json(visitorList, JsonRequestBehavior.AllowGet);
        }

        public JsonResult IsVisitorEmailExist(string email)
        {
            bool isExist = false;
            if (dbContext.VisitorRegistrations.Any(o => o.VisitorEmail == email))
            {
                isExist = true;
            }
            return Json(!isExist, JsonRequestBehavior.AllowGet);
        }

        public JsonResult IsVisitorContactNoExist(string contactNo)
        {
            bool isExist = false;
            if (dbContext.VisitorRegistrations.Any(o => o.VisitorContactNo == contactNo))
            {
                isExist = true;
            }
            return Json(!isExist, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ShowEventReportGenderWise()
        {
            if (Session["Id"] == null)
            {
                return RedirectToAction("Login", "Home")
                    ;
            }
            return View();
        }

        public ActionResult ShowDateWiseEventReportByGender(DateTime frmDate, DateTime edDate, string gender)
        {

            var query = dbContext.Events // your starting point - table in the "from" statement
                .Join(dbContext.VisitorRegistrations, // the source table of the inner join
                    post => post.EventId,
                    // Select the primary key (the first part of the "on" clause in an sql "join" statement)
                    meta => meta.EventId, // Select the foreign key (the second part of the "on" clause)
                    (post, meta) => new {Events = post, VisitorRegistrations = meta}) // selection
                .Where(
                    postAndMeta =>
                        postAndMeta.Events.EventDate >= frmDate && postAndMeta.Events.EventDate <= edDate &&
                        postAndMeta.VisitorRegistrations.Gender == gender).ToList();
            List<GenderWiseEventViewModel> alList = new List<GenderWiseEventViewModel>();
            foreach (var data in query)
            {
                GenderWiseEventViewModel model = new GenderWiseEventViewModel();
                model.EventId = data.Events.EventId;
                model.TotalVisitor = 1;
                bool containsItem = false;

                containsItem = alList.Any(item => item.EventId == model.EventId);
                if (containsItem)
                {
                    GenderWiseEventViewModel obj = alList.FirstOrDefault(x => x.EventId == model.EventId);

                    obj.EventName = data.Events.EventName;
                    obj.TotalVisitor += 1;
                    obj.EventDate = data.Events.EventDate.ToString();
                    DateTime a1 = DateTime.Now;
                    DateTime b1 = data.VisitorRegistrations.DateOfBirth;
                    var day1 = (a1 - b1).Days;
                    if (day1 <= 9125)
                    {
                        obj.ZeroToTwentyFiveCount += 1;
                    }
                    if (day1 > 9125 && day1 <= 14600)
                    {
                        obj.TwentySixToFortyCount += 1;
                    }
                    if (day1 > 14600)
                    {
                        obj.FortyAboveCount += 1;
                    }
                    int index = alList.IndexOf(alList.Where(x => x.EventId == obj.EventId).FirstOrDefault());
                    alList.RemoveAt(index);
                    alList.Add(obj);
                }
                else
                {
                    model.EventName = data.Events.EventName;
                    model.EventDate = data.Events.EventDate.ToString();
                    DateTime a = DateTime.Now;
                    DateTime b = data.VisitorRegistrations.DateOfBirth;
                    var day = (a - b).Days;
                    if (day <= 9125)
                    {
                        model.ZeroToTwentyFiveCount += 1;
                    }
                    if (day > 9125 && day <= 14600)
                    {
                        model.TwentySixToFortyCount += 1;
                    }
                    if (day > 14600)
                    {
                        model.FortyAboveCount += 1;
                    }

                    alList.Add(model);
                }




            }

            return Json(alList, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Dashboard()
        {
            if (Session["Id"] == null)
            {
                return RedirectToAction("Login", "Home")
                    ;
                
            }
            var list = dbContext.Events.Where(x => x.EventDate == DateTime.Today).ToList();
            int totalEvent = list.Count;
            ViewBag.TotalEvent = totalEvent;
            var visitorList=dbContext.Events // your starting point - table in the "from" statement
                .Join(dbContext.VisitorRegistrations, // the source table of the inner join
                    post => post.EventId,
                    // Select the primary key (the first part of the "on" clause in an sql "join" statement)
                    meta => meta.EventId, // Select the foreign key (the second part of the "on" clause)
                    (post, meta) => new {Events = post, VisitorRegistrations = meta}) // selection
                .Where(
                    postAndMeta =>
                        postAndMeta.Events.EventDate ==DateTime.Today ).ToList();
            int visitorTotal = visitorList.Count;
            ViewBag.TotalVisitor = visitorTotal;
            int maleVisitor=0;
            int femaleVisitor=0;
            foreach (var visitor in visitorList)
            {
                if (visitor.VisitorRegistrations.Gender=="Male")
                {
                    maleVisitor += 1;
                }
                else
                {
                    femaleVisitor += 1;
                }
            }
            ViewBag.Male = maleVisitor;
            ViewBag.Female = femaleVisitor;

            return View();

        }
    }
}

EventManagementSystem/Views/Event/CreateEvent.cshtml
@model EventManagementSystem.Models.Event

@{
    ViewBag.Title = "CreateEvent";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="text-align: center; color: maroon">Event Information Entry</h2>


@using (Html.BeginForm(null, null, FormMethod.Post, new { name = "EventForm", id = "EventForm" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)
        <div class="form-group">
            <label id="Name" class="control-label col-md-4"></label>
            <div class="col-md-8">
                <label id="EventName2">Event Name</label>
                @Html.TextBoxFor(m => m.EventName, new { @id = "EventName1", placeholder = " Enter Event Name", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EventName)
            </div>
        </div>

        <div class="form-group">
            <label id="Name" class="control-label col-md-4"></label>
            <div class="col-md-8">
                <label id="EventVenue2">Event Venue</label>
                @Html.TextBoxFor(m => m.EventVenue, new { @id = "EventVenue1", placeholder = " Enter Event Venue", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EventVenue)
            </div>
        </div>


        <div class="form-group">
            <label id="Name" class="control-label col-md-4"></label>
            <div class="col-md-8">
                <label id="Email2">Organizer Email</label>
                @Html.TextBoxFor(m => m.OrganizerEmail, new { @id = "Email1", placeholder = " Enter Organizer Email", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.OrganizerEmail)
            </div>
        </div>

        <div class="form-group">
            <label id="Name" class="control-label col-md-4"></label>
            <div class="col-md-8">
                <label id="ContactNo2">Organizer Contact No</label>
                @Html.TextBoxFor(m => m.ContactNo, new { @id = "ContactNo1", placeholder = " Enter Organizer Contact No", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ContactNo)
            </div>
        </div>

        

        <div class="form-group">
            <label id="Name" class="control-label col-md-4"></label>
            <div class="col-md-8">
                <label id="EventDate1">Event Date</label>
                <input type="date" name="EventDate" id="EventDate" class="form-control" placeholder="Event Date" />
                @Html.ValidationMessageFor(model => model.EventDate)
            </div>
        </div>

        <div class="form-group">
            <label id="Name" class="control-label col-md-4"></label>
            <div class="col-md-8">
                <label id="StartTime1">Start Time</label>
                <input type="time" name="StartTime" id="StartTime" class="form-control" placeholder="Start Time" />
                @Html.ValidationMessageFor(model => model.StartTime)
            </div>
        </div>

        <div class="form-group">
            <label id="Name" class="control-label col-md-4"></label>
            <div class="col-md-8">
                <label id="EndTime1">End Time</label>
                <input type="time" name="EndTime" id="EndTime" class="form-control" placeholder="End Time" />
                @Html.ValidationMessageFor(model => model.EndTime)
            </div>
        </div>

        <div class="form-group">
            <label id="Name" class="control-label col-md-4"></label>
            <div class=" col-md-8">
                <input type="button" value="Save" id="submit" class="btn btn-default" style="background-color: #4CAF50;color: white" />
                <input type="button" id="Cancel" value="Clear" class="btn btn-default" style="background-color: #FF0000; color: white" />
            </div>
        </div>
    </div>
}
<h3 style="text-align: center; color: green"><label id="displayMsg"></label> </h3>



@section Scripts {
    @*@Scripts.Render("~/bundles/jqueryval")*@
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.timepicker.min.js"></script>
    <script src="~/Scripts/jquery-ui-timepicker-addon.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#Name2').hide();
            $('#Email2').hide();
            $('#ContactNo2').hide();
            $('#EventName2').hide();
            $('#EventVenue2').hide();
            $('#EventDate1').hide();
            $('#StartTime1').hide();
            $('#EndTime1').hide();

            $('#Cancel').click(function () {
                $('#Name1').val('');
                $('#Email1').val('');
                $('#ContactNo1').val('');
                $('#EventVenue1').val('');
                $('#EventDate').val('');
                $('#StartTime').val('');
                $('#EndTime').val('');
                $('#EventName1').val('');
                $('#displayMsg').hide();
            });
            $('#Name1').click(function () {
                $('#Name2').show();

            });
            $('#Email1').click(function () {
                $('#Email2').show();

            });
            $('#ContactNo1').click(function () {
                $('#ContactNo2').show();

            });
            $('#EventName1').click(function () {
                $('#EventName2').show();

            });
            $('#EventVenue1').click(function () {
                $('#EventVenue2').show();

            });
            $('#EventDate').click(function () {
                $('#EventDate1').show();

            });
            $('#StartTime').click(function () {
                $('#StartTime1').show();

            });
            $('#EndTime').click(function () {
                $('#EndTime1').show();

            });
            $("#submit").click(function () {
                var email = $("#Email1").val();
                var cno = $("#ContactNo1").val();
                var ename = $("#EventName1").val();
                var venue = $("#EventVenue1").val();
                var startTime1 = $("#StartTime").val();
                var endTime1 = $("#EndTime").val();
                var date = $("#EventDate").val();

                var hour = parseInt(startTime1.substr(0, 2));
                var minute = parseInt(startTime1.substr(3, 5));
                var startTime = hour * 60 + minute;

                hour = parseInt(endTime1.substr(0, 2));
                minute = parseInt(endTime1.substr(3, 5));
                var endTime = hour * 60 + minute;

                if (startTime == endTime) {
                    $("#displayMsg").text("Its not Possible to create Zero Minute Duration class");
                }

                if (startTime < endTime) {

                    var jsonData = { OrganizerEmail: email, ContactNo: cno, EventName: ename, EventVenue: venue, StartTime: startTime1, EndTime: endTime1,  EventDate: date };

                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("CreateEvent", "Event")',
                        contentType: "application/json; charset=utf-8",
                        data: JSON.stringify(jsonData),
                        dataType: "json",
                        success: function (data) {
                            $("#displayMsg").text(data);

                        }
                    });

                }
                if (startTime > endTime) {
                    $("#displayMsg").text("Start time must be less than end time");

                }



            });
        });
    </script>
}

EventManagementSystem/Views/Event/ShowDateWiseEvent.cshtml
@{
    ViewBag.Title = "ShowDateWiseEvent";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="text-align: center; color: green">Show Date Wise Event</h2>
<form id="eventForm">
    <label>Start Date</label>
    <input type="date" id="startDate" />
    <label>End Date</label>
    <input type="date" id="endDate" />
    <input type="button" id="Show" value="Show" class="btn btn-default" style="background-color: #4CAF50; color: white" />
</form>
<br />
<div class="amount" id="aaa">
    <label style="color: #4CAF50">Total Event</label>
    <input type="text" name="amount" id="amount" value="" disabled="disabled" style="text-align: center"/>
</div>
<br/>


<form>
    <table class="table table-striped table-bordered table-hover" id="tableId">
        <thead>
            <tr>
                <th style="text-align: center">Event Name</th>
                <th style="text-align: center">Venue </th>
                <th style="text-align: center">Date</th>
                <th style="text-align: center">Start Time</th>
                <th style="text-align: center">End Time</th>

            </tr>
        </thead>
        <tbody id="EventTableBody"></tbody>


    </table>
</form>
<h3 style="text-align: center; color: green"><label id="displayMsg"></label> </h3>



@section scripts
{

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
    <script>
        $(document).ready(function () {
            $("#tableId").hide();
            $("#aaa").hide();
            
            $('#eventForm').validate({
                rules: {
                    startDate: "Required",
                    endDate: "Required",
        }
            });
            $('#Show').click(function () {
                $("#tableId").show();
                $("#aaa").show();
                $("#EventTableBody").empty();
                var fromDate = $('#startDate').val();
                var toDate = $('#endDate').val();
                var startdate = Date.parse(fromDate);
                var enddate = Date.parse(toDate);
        
                if (startdate > enddate) {
                    $("#displayMsg").text("Start Date must be less than End Date");
                }
                else {

                    var jsonData = { frmDate:fromDate, edDate: toDate };
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("ShowDateWiseEventByRange", "Event")',

                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(jsonData),
                    dataType: "json",
                    success: function (data) {
                        $('#amount').val(data.length);
                        $.each(data, function (key, value) {
                            var dateFormatted = new Date(parseInt(value.EventDate.substr(6))).toDateString();
                            $("#EventTableBody").append('<tr><td>' + value.EventName + '</td><td>' + value.EventVenue + '</td><td>' + dateFormatted + '</td><td>' + value.StartTime + '</td><td>' + value.EndTime + '</td></tr>');
                        });
                    }


                });

            }

            });

        });
    </script>
}

EventManagementSystem/Views/Event/ShowEventReportGenderWise.cshtml
@{
    ViewBag.Title = "ShowEventReportGenderWise";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="text-align: center; color: #4CAF50;">View Event Report Gender Wise</h2>
<br/>

<form id="eventForm">
    &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
    <label>Start Date</label>
    <input type="date" id="startDate" />
    &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
    <label>End Date</label>
    <input type="date" id="endDate"/>
    <br/>
    <br/>
    &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
    <label class="radio-inline">
        <input type="radio" name="gender" id="gender" value="Male" checked>Male
    </label>
    &emsp;&emsp;
    <label class="radio-inline">
        <input type="radio" name="gender" id="gender" value="Female">Female
    </label>
    &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
    <input type="button" id="Show" value="Show Report" class="btn btn-default" style="background-color: #4CAF50; color: white" />
</form>
<br/>

<form>
    <table class="table table-striped table-bordered table-hover" id="tableId">
        <thead>
            <tr>
                <th style="text-align: center">Event Name</th>
                <th style="text-align: center">Event Date </th>
                <th style="text-align: center">Total Visitor</th>
                <th style="text-align: center">AGE(0-25)</th>
                <th style="text-align: center">AGE(26-40)</th>
                <th style="text-align: center">AGE(40+)</th>

            </tr>
        </thead>
        <tbody id="EventTableBody"></tbody>


    </table>
</form>
<h3 style="text-align: center ; color: green"><label id="displayMsg"></label> </h3>

@section scripts
{
    
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    
    <script>
        $(document).ready(function() {
            $('#Show').click(function () {
                $("#tableId").show();
                $("#aaa").show();
                $("#EventTableBody").empty();
                var fromDate = $('#startDate').val();
                var toDate = $('#endDate').val();
                var checkedradio = $('[name="gender"]:radio:checked').val();
                var startdate = Date.parse(fromDate);
                var enddate = Date.parse(toDate);
                if (startdate > enddate) {
                    $("#displayMsg").text("Start Date must be less than End Date");
                } 
                else {

                    var jsonData = { frmDate: fromDate, edDate: toDate, gender: checkedradio };
                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("ShowDateWiseEventReportByGender", "Event")',

                        contentType: "application/json; charset=utf-8",
                        data: JSON.stringify(jsonData),
                        dataType: "json",
                        success: function (data) {
                            $.each(data, function (key, value) {
                                //var dateFormatted = new Date(parseInt(value.EventDate.substr(6))).toDateString();
                                $("#EventTableBody").append('<tr><td>' + value.EventName + '</td><td>' + value.EventDate + '</td><td>' + value.TotalVisitor + '</td><td>' + value.ZeroToTwentyFiveCount + '</td><td>' + value.TwentySixToFortyCount + '</td><td>' + value.FortyAboveCount + '</td>');
                            });
                        }


                    });

                }

            });
        });
    </script>
}

EventManagementSystem/Views/Event/ShowEventWiseReport.cshtml
@{
    ViewBag.Title = "ShowEventWiseReport";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="text-align: center;color: green">View  Event  Report</h2>

<form id="eventForm">
    <select name="eventId" id="eventId">
        <option value="">--Select Event--</option>
        @foreach (var eEvent in ViewBag.EventList)
        {
            <option value="@eEvent.EventId">@eEvent.EventName</option>
        }
    </select>
    &nbsp
    <input type="button" id="Show" value="View Report" class="btn btn-default" style="background-color: #4CAF50; color: white; text-align: center" />
</form>
<br />



<form>
    <table class="table table-striped table-bordered table-hover" id="tableId">
        <thead>
            <tr>
                <th style="text-align: center">Visitor Name </th>
                <th style="text-align: center">Visitor Email </th>
                <th style="text-align: center">Visitor Contact No</th>
                <th style="text-align: center">Gender</th>

            </tr>
        </thead>
        <tbody id="EventTableBody"></tbody>


    </table>
</form>
<div class="amount" id="aaa" style="text-align: right">
    <label style="color: #4CAF50">Total Visitor</label>
    <input type="text" name="amount" id="amount" value="" disabled="disabled" />
</div>
<br />
<h3 style="text-align: center; color: green"><label id="displayMsg"></label> </h3>
@section scripts
{
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#aaa').hide();
            $('#tableId').hide();
            $('#Show').click(function () {
                var eId = $('#eventId').val();
                var jsonData = { eventID: eId };
                $('#tableId').show();
                $('#EventTableBody').empty();
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetEventVisitorByEventId", "Event")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(jsonData),
                    dataType: "json",
                    success: function (data) {
                        if (data.length==0) {
                            $('#displayMsg').text('Sorry no visitor attended in this event');
                        }
                        $("#amount").val(data.length);
                        $.each(data, function (key, value) {
                            $("#EventTableBody").append('<tr><td>' + value.VisitorName + '</td><td>' + value.VisitorEmail + '</td><td>' + value.VisitorContactNo + '</td><td>' + value.Gender + '</td>');
                        });


                    }
                });
            });
        });
    </script>
}